# Generated by Django 5.2.17 on 2026-08-30 04:31

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='expires_at',
            field=models.DateTimeField(default=commerce.models.checkout_expiry),
        ),
    ]
