# Generated by Django 5.2.17 on 2026-08-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_seed_shipping_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='inventory_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
