# Generated by Django 5.2.17 on 2026-09-04 12:49

import archives.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('release', 'News release'), ('update', 'Update')], default='article', max_length=12)),
                ('topic', models.CharField(blank=True, help_text='Optional topic, e.g. Ingredients or Behind the scenes.', max_length=60)),
                ('excerpt', models.TextField(help_text='A short introduction for the feed and search results.', max_length=500)),
                ('author_name', models.CharField(default='Organic Emperor', max_length=120)),
                ('cover_image', models.ImageField(blank=True, upload_to='archives/covers/%Y/%m/')),
                ('cover_alt', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, help_text='Required when published. A future time schedules the post automatically.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='archives_po_status_c2b978_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Sections appear in ascending order.')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('quote', 'Quote'), ('image', 'Image'), ('video', 'Uploaded video'), ('embed', 'YouTube / Vimeo video')], default='text', max_length=12)),
                ('text', models.TextField(blank=True, help_text='Plain text, heading, or quote. Blank lines separate paragraphs; HTML is not rendered.')),
                ('image', models.ImageField(blank=True, upload_to='archives/images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('video', models.FileField(blank=True, upload_to='archives/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), archives.models.validate_video_size])),
                ('video_url', models.URLField(blank=True, help_text='HTTPS YouTube or public Vimeo URL.')),
                ('caption', models.CharField(blank=True, help_text='Image/video caption or quote attribution.', max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='archives.post')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
